import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, basename } from 'path';
import matter from 'gray-matter';
import { marked } from 'marked';

const BLOG_DIR = join(import.meta.dirname, '..', 'src', 'content', 'blog');
const OUTPUT_DIR = join(import.meta.dirname, '..', 'src', 'app', 'features', 'writing', 'data');
const OUTPUT_FILE = join(OUTPUT_DIR, 'blog-posts.generated.ts');

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

const files = readdirSync(BLOG_DIR).filter((f) => f.endsWith('.md'));

const posts = files.map((file) => {
  const raw = readFileSync(join(BLOG_DIR, file), 'utf-8');
  const { data, content } = matter(raw);
  const html = marked(content);
  const words = content.split(/\s+/).length;
  const readingTime = Math.max(1, Math.round(words / 200));
  const slug = basename(file, '.md');

  return {
    slug,
    title: data.title || slug,
    date: data.date || new Date().toISOString().split('T')[0],
    excerpt: data.excerpt || '',
    tags: data.tags || [],
    readingTime,
    published: data.published !== false,
    content: html,
  };
});

const output = `// Auto-generated by scripts/build-blog.mjs — do not edit manually
import { BlogPost } from '../../../core/models/blog-post.model';

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`Generated ${posts.length} blog posts → ${OUTPUT_FILE}`);
